---
title: "第3回課題レポート：区間推定と検定"
output: 
  pdf_document:
    latex_engine: xelatex
documentclass: bxjsarticle
classoption: xelatex,ja=standard
date: "2025-12-08"
---

```{r setup, include=FALSE}
# セットアップ（ここはいじらない）
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  dev = "cairo_pdf",
  dev.args = list(family = "Noto Sans CJK JP")
)

# 必要なパッケージ
library(tidyverse)
library(car)
```

```{r import_data}
# データの読み込み
data <- read_csv("u001.csv")

# 性別を因子型（カテゴリー）に変換しておく
data$sex <- as.factor(data$sex)
```
「男は仕事、女は家庭」という考え方に、みんな賛成か反対か？
```{r t-kentei}
# 変数の作成
data$genderrole <- data$ZQ39A

# リコード：数値を反転し、6(非該当)と9(無回答)をNAに
data$genderrole <- recode(data$genderrole, '1=5; 2=4; 4=2; 5=1; c(6,9)=NA')

# データの確認
table(data$ZQ39A, data$genderrole, useNA = 'ifany')

# 母平均のt検定
# 帰無仮説：平均 = 3（どちらともいえない）
# 対立仮説：平均 =! 3
t.test(data$genderrole, mu=3)
```

#考察

平均値2.55は3より有意に低く、帰無仮説は棄却される。よって全体として、世の中の人は性別役割分業（男は仕事、女は家庭）にはどちらかと言えば反対している

失業経験者の割合は15%と言えるか？
```{r bohiritu-kenntei}
# 変数の作成（あり=1, なし=0）
data$fired <- data$ZQ11_E
data$fired <- recode(data$fired, '1=1; 2=0')

# 集計結果の確認
table(data$fired)

# 母比率の検定
# 標本での経験者数139人、全体1000人
# 帰無仮説：母比率 = 0.15
prop.test(139, 1000, p = 0.15, alternative = "two.sided")
```
#考察

P値が0.05より大きいので帰無仮説は棄却できない。今回のデータの失業率は誤差の範囲内といえる。

男性と女性で、考え方に差はあるか？
```{r 2hyouhonn-kenntei}
# 性別ごとの要約統計量
tapply(data$genderrole, data$sex, summary)

# 2標本t検定
# 帰無仮説：男性と女性の平均値に差はない
t.test(data$genderrole ~ data$sex)
```
#考察

p値が0.05より非常に小さいため帰無仮説は棄却される。よって男性の方が女性よりも、性別役割分業に対して保守的である
